### ISSUE TITLE
Vekkama Ille !?

### ISSUE THREAD

**Issue by iampragath** [Ananthakr/AndroidLabWeek4#1]
Hello,

I very much appreciate your contribution towards this lab. Yet, `Green` ah room ku vanthu Star kekuriye !

How do I tell this !!!???

**Comment by Ananthakr** [comment]
Ila. Code copy adikriye unaku vekkama Ile?

**Comment by iampragath** [comment]
No.

Technically speaking what you did was integration of multiple posts in tutorials point. All the code was not written by yourself and this lab doesn't require you to do so.

If I am accused of Copying then you also should be done so.
